#!/usr/bin/env bash
###############################################################################
# .nbrc
#
# Configuration file for `nb`, a command line note-taking, bookmarking,
# and knowledge base application with encryption, search, Git-backed syncing,
# and more in a single portable script.
#
# Edit this file manually or manage settings using the `nb settings`
# subcommand. Configuration options are set as environment variables, eg:
#   export NB_ENCRYPTION_TOOL=gpg
#
# https://github.com/xwmx/nb
###############################################################################
export EDITOR=nvim

export NB_MARKDOWN_TOOL='bat'
export NB_SYNTAX_THEME="${NB_SYNTAX_THEME:-Catppuccin Mocha}"

export NB_AUTO_SYNC="${NB_AUTO_SYNC:-0}" # Set by `nb` • 2026年  7月  4日 土曜日 09:47:44 JST
