[[plugins]]
repo = 'prabirshrestha/vim-lsp'
hook_add = '''
nnoremap <silent> <C-n> :<C-u>LspNextDiagnostic<CR>
nnoremap <silent> <C-p> :<C-u>LspPreviousDiagnostic<CR>

let g:lsp_document_code_action_signs_enabled = 0
let g:lsp_diagnostics_float_cursor = 1
let g:lsp_diagnostics_virtual_text_enabled = 0
highlight lspReference ctermfg=white guifg=red ctermbg=blue guibg=green
'''

[[plugins]]
repo = 'mattn/vim-lsp-settings'
hook_add = '''
let g:lsp_settings_filetype_ruby = ['solargraph', 'steep']
'''

# [[plugins]]
# repo     = 'Shougo/deoplete.nvim'
# hook_add = '''
# let g:deoplete#enable_at_startup = 1
# call deoplete#custom#option({
# \   'auto_complete_delay': 0,
# \   'min_pattern_length': 2,
# \ })
# '''

# [[plugins]]
# repo = 'lighttiger2505/deoplete-vim-lsp'

[[plugins]]
repo = 'prabirshrestha/asyncomplete.vim'

[[plugins]]
repo = 'prabirshrestha/asyncomplete-lsp.vim'

[[plugins]]
repo     = 'Shougo/denite.nvim'
hook_add = '''
" Define mappings
autocmd FileType denite call s:denite_my_settings()
function! s:denite_my_settings() abort
  nnoremap <silent><buffer><expr> <CR> denite#do_map('do_action')
  nnoremap <silent><buffer><expr> d denite#do_map('do_action', 'delete')
  nnoremap <silent><buffer><expr> p denite#do_map('do_action', 'preview')
  nnoremap <silent><buffer><expr> q denite#do_map('quit')
  nnoremap <silent><buffer><expr> i denite#do_map('open_filter_buffer')
  nnoremap <silent><buffer><expr> <Space> denite#do_map('toggle_select').'j'
endfunction

nnoremap [denite] <Nop>
nmap <Space>u [denite]
nnoremap <silent> [denite]u :<C-u>Denite buffer file_mru<CR>
nnoremap <silent> [denite]b :<C-u>Denite buffer<CR>
nnoremap <silent> [denite]h :<C-u>Denite file_mru<CR>
nnoremap <silent> [denite]g :<C-u>Denite file<CR>
nnoremap <silent> [denite]f :<C-u>DeniteBufferDir file<CR>
'''

[[plugins]]
repo = 'Shougo/neomru.vim'

[[plugins]]
repo     = 'rust-lang/rust.vim'
hook_add = 'let g:rustfmt_autosave = 1'

[[plugins]]
repo     = 'racer-rust/vim-racer'
hook_add = '''
au FileType rust nmap gd <Plug>(rust-def)
au FileType rust nmap gs <Plug>(rust-def-split)
au FileType rust nmap gx <Plug>(rust-def-vertical)
au FileType rust nmap <leader>gd <Plug>(rust-doc)
'''

[[plugins]]
repo     = 'tpope/vim-fugitive'
hook_add = '''
nnoremap [fugitive]  <Nop>
nmap <space>g [fugitive]
nnoremap <silent> [fugitive]s :Git status<CR>
nnoremap <silent> [fugitive]a :Git write<CR>
nnoremap <silent> [fugitive]c :Git commit<CR>
nnoremap <silent> [fugitive]b :Git blame<CR>
nnoremap <silent> [fugitive]d :Git diff<CR>
nnoremap <silent> [fugitive]m :Git merge<CR>
'''

[[plugins]]
repo     = 'airblade/vim-gitgutter'
hook_add = '''
let g:gitgutter_sign_added = "∙"
highlight GitGutterAdd ctermfg=green guifg=green
highlight GitGutterDelete ctermfg=green guifg=green
'''

[[plugins]]
repo = 'junegunn/goyo.vim'

[[plugins]]
repo = 'cespare/vim-toml'

# [[plugins]]
# repo = 'junegunn/fzf.vim'

[[plugins]]
repo     = 'vim-airline/vim-airline'
hook_add = '''
let g:airline_symbols_ascii = 1
let g:airline#extensions#tabline#enabled = 1
let g:airline#extensions#whitespace#mixed_indent_algo = 1
'''

[[plugins]]
repo     = 'vim-airline/vim-airline-themes'
hook_add = '''
" let g:airline_theme = 'dark'
" let g:airline_theme = 'molokai'
let g:airline_theme = 'papercolor'
'''

[[plugins]]
repo = 'dart-lang/dart-vim-plugin'
hook_add = '''
let g:dart_style_guide = 2
let g:dart_format_on_save = 1
'''

# [[plugins]]
# repo = 'thosakwe/vim-flutter'

