[[plugins]]
repo     = 'Shougo/deoplete.nvim'
hook_add = 'let g:deoplete#enable_at_startup = 1'

[[plugins]]
repo = 'roxma/vim-hug-neovim-rpc'

[[plugins]]
repo = 'roxma/nvim-yarp'

[[plugins]]
repo     = 'Shougo/denite.nvim'
hook_add = '''
" Define mappings
autocmd FileType denite call s:denite_my_settings()
function! s:denite_my_settings() abort
  nnoremap <silent><buffer><expr> <CR>
  \ denite#do_map('do_action')
  nnoremap <silent><buffer><expr> d
  \ denite#do_map('do_action', 'delete')
  nnoremap <silent><buffer><expr> p
  \ denite#do_map('do_action', 'preview')
  nnoremap <silent><buffer><expr> q
  \ denite#do_map('quit')
  nnoremap <silent><buffer><expr> i
  \ denite#do_map('open_filter_buffer')
  nnoremap <silent><buffer><expr> <Space>
  \ denite#do_map('toggle_select').'j'
endfunction

nnoremap [denite] <Nop>
nmap <Space>u [denite]
nnoremap <silent> [denite]u :<C-u>Denite buffer file_mru<CR>
nnoremap <silent> [denite]b :<C-u>Denite buffer<CR>
nnoremap <silent> [denite]h :<C-u>Denite file_mru<CR>
nnoremap <silent> [denite]g :<C-u>Denite file<CR>
nnoremap <silent> [denite]f :<C-u>DeniteBufferDir file<CR>
'''

[[plugins]]
repo = 'Shougo/neomru.vim'

[[plugins]]
repo     = 'rust-lang/rust.vim'
hook_add = '''
let g:rustfmt_autosave = 1
set hidden
'''

[[plugins]]
repo     = 'racer-rust/vim-racer'
hook_add = '''
au FileType rust nmap gd <Plug>(rust-def)
au FileType rust nmap gs <Plug>(rust-def-split)
au FileType rust nmap gx <Plug>(rust-def-vertical)
au FileType rust nmap <leader>gd <Plug>(rust-doc)
'''

[[plugins]]
repo     = 'scrooloose/nerdtree'
hook_add = 'nnoremap <C-\> :NERDTreeToggle<CR>'

[[plugins]]
repo = 'w0rp/ale'

[[plugins]]
repo     = 'davidhalter/jedi-vim'
hook_add = '''
let g:jedi#popup_on_dot=0
let g:jedi#popup_select_first=0
let g:jedi#goto_assignments_command="<leader>a"
" let g:jedi#show_call_signatures=2
autocmd FileType python setlocal completeopt-=preview
'''

[[plugins]]
repo     = 'tpope/vim-fugitive'
hook_add = '''
nnoremap [fugitive]  <Nop>
nmap <space>g [fugitive]
nnoremap <silent> [fugitive]s :Gstatus<CR>
nnoremap <silent> [fugitive]a :Gwrite<CR>
nnoremap <silent> [fugitive]c :Gcommit-v<CR>
nnoremap <silent> [fugitive]b :Gblame<CR>
nnoremap <silent> [fugitive]d :Gdiff<CR>
nnoremap <silent> [fugitive]m :Gmerge<CR>
'''

[[plugins]]
repo = 'junegunn/goyo.vim'

[[plugins]]
repo = 'cespare/vim-toml'

[[plugins]]
repo = 'junegunn/fzf.vim'

[[plugins]]
repo     = 'vim-airline/vim-airline'
hook_add = '''
nnoremap <silent> <C-l> :<C-u>bnext<CR>
nnoremap <silent> <C-h> :<C-u>bprevious<CR>
let g:airline#extensions#tabline#enabled = 1
let g:airline#extensions#whitespace#mixed_indent_algo = 1
'''

[[plugins]]
repo     = 'vim-airline/vim-airline-themes'
hook_add = '''
let g:airline_theme = 'molokai'
" let g:airline_theme = 'papercolor'
'''

# [[plugins]]
# repo     = 'vim-latex/vim-latex'
# hook_add = '''
# let g:Tex_AutoFolding = 0
# '''
# 
# [[plugins]]
# repo     = 'suan/vim-instant-markdown'
# hook_add = '''
# let g:instant_markdown_slow = 1
# let g:instant_markdown_autostart = 0
# '''
