# [[plugins]]
# repo = 'prabirshrestha/vim-lsp'
# hook_add = '''
# let g:lsp_document_code_action_signs_enabled = 0
# '''

# [[plugins]]
# repo = 'mattn/vim-lsp-settings'

# [[plugins]]
# repo = 'prabirshrestha/asyncomplete.vim'

# [[plugins]]
# repo = 'prabirshrestha/asyncomplete-lsp.vim'

# [[plugins]]
# repo = 'Shougo/neomru.vim'

# [[plugins]]
# repo     = 'rust-lang/rust.vim'
# hook_add = 'let g:rustfmt_autosave = 1'

# [[plugins]]
# repo     = 'racer-rust/vim-racer'

# [[plugins]]
# repo     = 'tpope/vim-fugitive'

[[plugins]]
repo     = 'airblade/vim-gitgutter'
hook_add = '''
let g:gitgutter_sign_added = "+"
let g:gitgutter_sign_modified = '^'
let g:gitgutter_sign_removed = '-'
highlight GitGutterAdd    guifg=#009900 ctermfg=2
highlight GitGutterChange guifg=#bbbb00 ctermfg=3
highlight GitGutterDelete guifg=#ff2222 ctermfg=1
highlight GitGutterAddLine          ctermbg=2
highlight GitGutterChangeLine       ctermbg=3
highlight GitGutterDeleteLine       ctermbg=1
" highlight GitGutterChangeDeleteLine ctermbg=
'''

[[plugins]]
repo = 'junegunn/goyo.vim'
hook_add = '''
let g:goyo_width = 100
" let g:goyo_height = 85%
" let g:goyo_linenr = 0
'''

[[plugins]]
repo = 'junegunn/limelight.vim'
hook_add = '''
autocmd! User GoyoEnter Limelight
autocmd! User GoyoLeave Limelight!
'''

[[plugins]]
repo = 'cespare/vim-toml'

# [[plugins]]
# repo = 'junegunn/fzf.vim'

[[plugins]]
repo     = 'vim-airline/vim-airline'
hook_add = '''
let g:airline_symbols_ascii = 1
let g:airline#extensions#tabline#enabled = 1
let g:airline#extensions#whitespace#mixed_indent_algo = 1
'''

[[plugins]]
repo     = 'vim-airline/vim-airline-themes'
hook_add = '''
" let g:airline_theme = 'dark'
" let g:airline_theme = 'molokai'
" let g:airline_theme = 'papercolor'
" let g:airline_theme = "raven"
let g:airline_theme = "iceberg"
'''

# [[plugins]]
# repo = 'dart-lang/dart-vim-plugin'
# hook_add = '''
# let g:dart_style_guide = 2
# let g:dart_format_on_save = 1
# '''

# [[plugins]]
# repo = 'thosakwe/vim-flutter'

# [[plugins]]
# repo = 'posva/vim-vue'

[[plugins]]
repo = 'cocopon/iceberg.vim'

[[plugins]]
repo = 'rbtnn/vim-ambiwidth'

[[plugins]]
repo = 'nordtheme/vim'

[[plugins]]
repo = 'lambdalisue/fern.vim'

[[plugins]]
repo = 'lambdalisue/fern-bookmark.vim'
