set ambiwidth=double
" set guifont=Migu\ 1M\ Regular\ 12
" set guifont=Migu\ 1M\ Bold\ 12
" set guifont=IPAGothic\ 12
" set guifont=IPAMincho\ 12
" set guifont=IPAMincho\ Bold\ 12
" set guifont=M+\ 1M\ medium\ 12
" set guifont=M\ PLUS\ 1\ Code\ Medium\ 12
" set guifont=M\ PLUS\ 2\ Medium\ 12
" set guifont=Noto\ Sans\ Mono\ CJK\ JP\ 12
set guifont=PlemolJP\ Console\ NF\ Medium\ 12
" set guifont=Source\ Han\ Mono\ M\ 12
" colorscheme iceberg
" colorscheme desert
colorscheme nord
" AirlineTheme papercolor
" AirlineTheme solarized
" AirlineTheme raven
" AirlineTheme nord
" colorscheme nord
" AirlineTheme iceberg
AirlineTheme nord
set lines=42
set columns=140
" set columns=180
" 左右・水平スクロールバーを非表示にする
set guioptions-=r
set guioptions-=R
set guioptions-=l
set guioptions-=L
set guioptions-=b
" if has('multi_byte_ime')
"   highlight Cursor guifg=NONE guibg=Green
"   highlight CursorIM guifg=NONE guibg=Purple
" endif
" nnoremap <leader><leader> :<C-u>call ToggleFontShape()<CR>
function! ToggleFontShape()
  if &guifont == "IPAGothic 12"
    " set Writing mode
    let &guifont="IPAMincho 12"
    let &guioptions=substitute(&guioptions,"T","","g")
    let &guioptions=substitute(&guioptions,"m","","g")
  elseif &guifont == "IPAMincho 12"
    " set Coding mode
    let &guifont="IPAGothic 12"
    if stridx(&guioptions, "T") == -1
      let &guioptions=&guioptions . "T"
    endif
    if stridx(&guioptions, "m") == -1
      let &guioptions=&guioptions . "m"
    endif
  else
    echo "unknown font"
  endif
endfunction
