set ambiwidth=double
" set guifont=Migu\ 1M\ 11
" set guifont=M+\ 1M\ medium\ 12
set guifont=M\ PLUS\ 1\ \Code\ Medium\ 12
" set guifont=Noto\ Sans\ Mono\ CJK\ JP\ 12
AirlineTheme papercolor
colorscheme desert
" colorscheme iceberg
set lines=40
set columns=120
" set columns=180
" 左右・水平スクロールバーを非表示にする
set guioptions-=r
set guioptions-=R
set guioptions-=l
set guioptions-=L
set guioptions-=b
" if has('multi_byte_ime')
"   highlight Cursor guifg=NONE guibg=Green
"   highlight CursorIM guifg=NONE guibg=Purple
" endif
