eval `opam config env`
export PATH=~/.cargo/bin:$PATH
export RUST_SRC_PATH=$(rustc --print sysroot)/lib/rustlib/src/rust/src
export PATH="$HOME/flutter/bin:$PATH"
export PATH="$HOME/android-studio/bin:$PATH"
# export CHROME_EXECUTABLE=/usr/bin/google-chrome-stable
export CHROME_EXECUTABLE=/usr/bin/chromium
